-- Per-language font customization
ALTER TABLE "SiteSettings" ADD COLUMN "fontFamilyKh" VARCHAR(100) NOT NULL DEFAULT 'Noto Sans Khmer';
ALTER TABLE "SiteSettings" ADD COLUMN "fontFamilyEn" VARCHAR(100) NOT NULL DEFAULT 'Inter';
ALTER TABLE "SiteSettings" ADD COLUMN "fontFamilyZh" VARCHAR(100) NOT NULL DEFAULT 'Huninn';
ALTER TABLE "SiteSettings" ADD COLUMN "fontSizeKh" INTEGER NOT NULL DEFAULT 16;
ALTER TABLE "SiteSettings" ADD COLUMN "fontSizeEn" INTEGER NOT NULL DEFAULT 16;
ALTER TABLE "SiteSettings" ADD COLUMN "fontSizeZh" INTEGER NOT NULL DEFAULT 16;
ALTER TABLE "SiteSettings" ADD COLUMN "fontWeightKh" INTEGER NOT NULL DEFAULT 400;
ALTER TABLE "SiteSettings" ADD COLUMN "fontWeightEn" INTEGER NOT NULL DEFAULT 400;
ALTER TABLE "SiteSettings" ADD COLUMN "fontWeightZh" INTEGER NOT NULL DEFAULT 400;
