import { randomUUID } from "crypto";
import fs from "fs";
import path from "path";
import sharp from "sharp";
import { env, r2Configured } from "../config/env";
import { logger } from "./logger";
import { getR2Client, R2_BUCKET, objectUrl, removeObject, putObject } from "./r2";

// ============================================================
// Media storage abstraction.
//   - Primary: Cloudflare R2 object storage (bucket `news-media`), with
//     server-side image variants generated by `sharp`:
//       thumbnail (300w) · small (640w) · medium (1024w) ·
//       large (1600w) · original (as uploaded)
//   - Fallback: local disk under backend/uploads (used when R2
//     is unavailable — uploads never break the app).
// The rest of the app only ever sees { url, objectKey, width,
// height, format, size, variants }.
// ============================================================

export interface StoredVariant {
  key: string;
  url: string;
  width: number;
  height: number;
}

export interface StoredFile {
  url: string;
  publicId: string | null;
  secureUrl: string | null;
  objectKey: string | null;
  width: number | null;
  height: number | null;
  format: string | null;
  size: number | null;
  variants: StoredVariant[];
}

const ALLOWED_FOLDERS = new Set(["articles", "categories", "authors", "ads", "gallery", "site"]);

/** Pick a safe storage folder; defaults to `articles`. */
export function normalizeFolder(folder: string | undefined | null): string {
  if (folder && ALLOWED_FOLDERS.has(folder)) return folder;
  return "articles";
}

function extFor(mime: string): string {
  const map: Record<string, string> = {
    "image/jpeg": "jpg",
    "image/png": "png",
    "image/webp": "webp",
    "image/gif": "gif",
    "image/svg+xml": "svg",
  };
  return map[mime] ?? "bin";
}

function safeName(originalname: string): string {
  const base = path.basename(originalname, path.extname(originalname))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
  return base || "image";
}

// ------------------------------------------------------------------
// Sharp variant generation (skipped for SVG/GIF to preserve animation)
// ------------------------------------------------------------------
const VARIANT_SIZES: { suffix: string; width: number }[] = [
  { suffix: "thumb", width: 300 },
  { suffix: "small", width: 640 },
  { suffix: "medium", width: 1024 },
  { suffix: "large", width: 1600 },
];

async function generateVariants(
  buffer: Buffer,
  mime: string
): Promise<{ variants: { buffer: Buffer; key: string; width: number; height: number }[]; width: number; height: number }> {
  if (mime === "image/svg+xml" || mime === "image/gif") {
    const meta = await sharp(buffer, { animated: mime === "image/gif" }).metadata();
    return {
      variants: [],
      width: meta.width ?? 0,
      height: meta.height ?? 0,
    };
  }

  const meta = await sharp(buffer).metadata();
  const width = meta.width ?? 0;
  const height = meta.height ?? 0;
  const variants: { buffer: Buffer; key: string; width: number; height: number }[] = [];

  for (const v of VARIANT_SIZES) {
    // Only generate variants smaller than the original to save space.
    if (width && v.width < width) {
      const resized = await sharp(buffer)
        .resize({ width: v.width, withoutEnlargement: true })
        .webp({ quality: 82 })
        .toBuffer();
      const vMeta = await sharp(resized).metadata();
      variants.push({
        buffer: resized,
        key: v.suffix,
        width: vMeta.width ?? 0,
        height: vMeta.height ?? 0,
      });
    }
  }

  return { variants, width, height };
}

// ------------------------------------------------------------------
// Cloudflare R2 upload
// ------------------------------------------------------------------
async function uploadToR2(buffer: Buffer, mime: string, originalname: string, folder: string): Promise<StoredFile> {
  const client = getR2Client();
  if (!client) throw new Error("R2 not configured");

  const id = randomUUID();
  const folderPath = normalizeFolder(folder);
  const ext = extFor(mime);
  const base = `${folderPath}/${safeName(originalname)}-${id}`;
  const mainKey = `${base}.${ext}`;

  const { variants, width, height } = await generateVariants(buffer, mime);

  await putObject(mainKey, buffer, mime);

  const storedVariants: StoredVariant[] = [];
  for (const v of variants) {
    const vKey = `${base}-${v.key}.webp`;
    await putObject(vKey, v.buffer, "image/webp");
    storedVariants.push({ key: vKey, url: objectUrl(vKey), width: v.width, height: v.height });
  }

  return {
    url: objectUrl(mainKey),
    publicId: null,
    secureUrl: objectUrl(mainKey),
    objectKey: mainKey,
    width: width || null,
    height: height || null,
    format: ext,
    size: buffer.length,
    variants: storedVariants,
  };
}

// ------------------------------------------------------------------
// Local disk fallback (R2 unavailable)
// ------------------------------------------------------------------
function ensureUploadsDir(): void {
  fs.mkdirSync(env.uploadsDir, { recursive: true });
}

async function uploadToDisk(buffer: Buffer, mime: string, originalname: string, folder: string): Promise<StoredFile> {
  ensureUploadsDir();
  const ext = extFor(mime);
  const folderPath = normalizeFolder(folder);
  const fileName = `${folderPath}-${safeName(originalname)}-${randomUUID()}.${ext}`;
  fs.writeFileSync(path.join(env.uploadsDir, fileName), buffer);

  let width: number | null = null;
  let height: number | null = null;
  try {
    const meta = await sharp(buffer).metadata();
    width = meta.width ?? null;
    height = meta.height ?? null;
  } catch {
    /* not a raster image (e.g. svg) — dimensions unknown */
  }

  return {
    url: `/uploads/${fileName}`,
    publicId: null,
    secureUrl: `/uploads/${fileName}`,
    objectKey: null,
    width,
    height,
    format: ext,
    size: buffer.length,
    variants: [],
  };
}

export async function storeImage(
  buffer: Buffer,
  mime: string,
  originalname = "image",
  folder?: string
): Promise<StoredFile> {
  if (r2Configured()) {
    try {
      return await uploadToR2(buffer, mime, originalname, folder ?? "articles");
    } catch (error) {
      logger.error({ error }, "R2 upload failed, falling back to local disk");
    }
  }
  return uploadToDisk(buffer, mime, originalname, folder ?? "articles");
}

export async function deleteStoredImage(
  objectKey: string | null,
  publicId: string | null,
  url: string | null
): Promise<void> {
  // R2: remove the main object and any generated variants (strip suffix).
  if (objectKey) {
    if (getR2Client()) {
      const base = objectKey.replace(/\.(jpg|png|webp|gif|svg)$/i, "");
      const keys = [objectKey, ...["thumb", "small", "medium", "large"].map((s) => `${base}-${s}.webp`)];
      await Promise.all(keys.map((k) => removeObject(k)));
      return;
    }
  }

  if (publicId) {
    // Legacy Cloudinary public id — nothing to delete (service retired).
    logger.warn({ publicId }, "Legacy publicId delete skipped (Cloudinary removed)");
  }

  if (url && url.startsWith("/uploads/")) {
    const file = path.join(env.uploadsDir, path.basename(url));
    try {
      fs.unlinkSync(file);
    } catch {
      /* file already gone */
    }
  }
}

/** Convenience wrapper matching the old (publicId, url) call sites. */
export async function deleteStoredByUrl(url: string | null): Promise<void> {
  if (!url) return;
  // R2 URLs contain the object key after the bucket name or public URL.
  const r2PublicUrl = env.r2.publicUrl;
  if (r2PublicUrl && url.startsWith(r2PublicUrl)) {
    const objectKey = url.slice(r2PublicUrl.length + 1);
    if (objectKey) return deleteStoredImage(objectKey, null, null);
  }
  const bucketPrefix = `/${R2_BUCKET}/`;
  const idx = url.indexOf(bucketPrefix);
  if (idx !== -1 && r2Configured()) {
    const objectKey = url.slice(idx + bucketPrefix.length);
    if (objectKey) return deleteStoredImage(objectKey, null, null);
  }
  return deleteStoredImage(null, null, url);
}
